use_frameworks!
inhibit_all_warnings!

target 'XSDCustomCardView_Example' do
  pod 'XSDCustomCardView', :path => '../'
	pod 'Masonry'
    pod 'SDWebImage'
  target 'XSDCustomCardView_Tests' do
    inherit! :search_paths

    
  end
end
